services:
  redis:
    image: redis/redis-stack:latest
    container_name: basic_panel_redis
    restart: always
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
    ports:
      - '6380:6379'
      - '8001:8001'

  mongodb:
    image: mongo:latest
    container_name: basic_panel_mongodb
    restart: always

    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: BasicPanelDB
    volumes:
      - ./utils/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
